name: 'ArgoCD Diff'
description: 'Diffs all ArgoCD apps in the repo, and provides the diff as a PR comment'
author: 'argocd-diff-action'
inputs:
  only-changed-apps:
    description: Only run diffs for ArgoCD Applications whose spec.source.path contains files changed in the pull request
    default: 'false'
    required: false
  argocd-server-fqdn: 
    description: ArgoCD server FQDN (i.e., without the protocol)
    required: true
  argocd-server-tls:
    description: Use TLS to communicate with ArgoCD
    default: 'true'
    required: false
  argocd-token: 
    description: ArgoCD token for a local or project-scoped user https://argoproj.github.io/argo-cd/operator-manual/user-management/#local-usersaccounts-v15
    required: true
  argocd-version: 
    description: '`argocd` command version to install. Defaults to the server version.'
    default: ''
    required: false
  github-token: 
    description: Github Token
    required: true
  argocd-extra-cli-args: 
    description: Extra arguments to pass to the argocd CLI
    default: --grpc-web
    required: false
  argocd-exclude-paths: 
    description: ArgoCD app paths to exclude in comma separated list
    default: ''
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
